name: CI
on:
  pull_request:
    branches: [develop, main]
  push:
    branches: [develop, main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: "14.17"
      - run: npm ci
      - run: npm test -- --coverage
        env:
          CI: true   
      - name: Upload Test Coverage
        uses: actions/upload-artifact@v1
        with:
          name: code-coverage
          path: coverage
      - name: Build Project
        if: github.event_name == 'push'
        run: npm run build 
      - name: Upload Build folder
        if: github.event_name == 'push'
        uses: actions/upload-artifact@v1
        with:
           name: build
           path: build           
      # - name: Deploy to Staging (can be AWS) to some test ENV
      # I will deploy code to the test AWS EC2
      # Tests 1) Smoke 5 minutes Test
    
      - name: Create a Release
        if: github.event_name == 'push'  && github.ref == 'refs/heads/main'
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.CUSTOM_TOKEN }}        